# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md LICENSE ./
COPY src ./src

# Install dependencies and the package
RUN pip install --no-cache-dir .

CMD ["imgflip-mcp"]
